### ISSUE TITLE
Link to prettier-vscode

### ISSUE THREAD

**Issue by CiGit** [bySabi/patch--prettier-vscode#1]
Could you please also patch repository.url in [package.json](https://github.com/prettier/prettier-vscode/blob/62b33e9c4d00b90331b6dfdc757580d479c1c3b9/package.json#L15).
I'd like to avoid having issues in https://github.com/prettier/prettier-vscode from this *fork*.
Thanks.

**Comment by bySabi** [comment]
Fixed!

Thanks for report it.
